### ISSUE TITLE
Could not read CA certificate "/etc/docker/ca.pem": open /etc/docker/ca.pem: no such file or directory

### ISSUE THREAD

**Issue by a1exus** [getcarina/carina#112] opened 2016-08-23 14:10 UTC
I added Docker Cluster to Carina, download & unzip _.ZIP_ file and _source docker.env_, yet I got following:

```
$ source docker.env 
$ docker ps
Could not read CA certificate "/etc/docker/ca.pem": open /etc/docker/ca.pem: no such file or directory
$ 
```

**Comment by carolynvs** [comment] 2016-08-23 14:18
After sourcing `docker.env` can you run `env | grep DOCKER` and paste the output? Also which shell are you using, bash?

For example, when I run that I see something like this:

```bash
DOCKER_HOST=tcp://104.130.0.55:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/carolynvs/.carina/clusters/carolynvs/mycluster
DOCKER_VERSION=1.11.1
```

**Comment by a1exus** [comment] 2016-08-23 14:21
certainly, see bellow:
```
$ env | grep DOCKER
DOCKER_HOST=tcp://146.20.69.115:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/home/X
DOCKER_VERSION=1.11.2
$ 
```
I masked my full path from `DOCKER_CERT_PATH`, I hope you don't mind.

**Comment by carolynvs** [comment] 2016-08-23 14:25
Sure not a problem! I just wanted to check that `DOCKER_CERT_PATH` was set to a real directory and not an empty string.

Can you list the files in `DOCKER_CERT_PATH`? It's odd that docker thinks that it should use `/etc/docker/ca.pem` instead of the `ca.pem` in the cert path.

e.g.

```
$ ls $DOCKER_CERT_PATH
README.md      	ca-key.pem     	ca.pem 		cert.pem       	docker.cmd     	docker.env     	docker.fish    	docker.ps1     	key.pem
```

**Comment by a1exus** [comment] 2016-08-23 14:27
Sure,
```
$ ls $DOCKER_CERT_PATH
ca-key.pem  ca.pem  cert.pem  docker.cmd  docker.env  docker.fish  docker.ps1  key.pem  README.md
$ 
```
FYI, I'm using:
```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
$ uname -a
Linux X 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ 
```

**Comment by carolynvs** [comment] 2016-08-23 14:32
Thanks! Let me spin up a centos vm quick and make sure there isn't anything wonky with that.

**Comment by carolynvs** [comment] 2016-08-23 15:08
I was able to reproduce the problem, it is a known bug with RedHat. https://bugzilla.redhat.com/show_bug.cgi?id=1346206

A workaround is to use the [Docker Version Manager (dvm)](https://github.com/getcarina/dvm). Here's what I did to install on RH and get it working:

1. Install dvm 

    `curl -sL https://download.getcarina.com/dvm/latest/install.sh | sh`.
2. Load dvm
 
    `source ~/.dvm/dvm.sh`

3. Load your cluster credentials

    `source docker.env`
4. Use the right version of the docker client to match the version of Docker on your cluster.

    `dvm use`
5. Do the Dockers

    `docker info`

**Comment by carolynvs** [comment] 2016-08-29 12:57
@a1exus I'm closing this issue because I think we've uncovered the problem and have a workaround. If you continue having trouble, just reopen this issue and let us know.

**Closed by carolynvs** 2016-08-29 12:57 UTC
Labels: awaiting user response, in progress

**Comment by marun** [comment] 2016-10-12 17:11
A simpler solution is to update ``/etc/sysconfig/docker`` to ensure that ``DOCKER_CERT_PATH`` is not overridden:

```
< DOCKER_CERT_PATH=/etc/docker
---
> if [ -z "${DOCKER_CERT_PATH}" ]; then
>   DOCKER_CERT_PATH=/etc/docker
> fi
```

**Comment by a1exus** [comment] 2016-10-12 17:26
I'll try it when I get back to office)
